server:
  port: 8083

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5435/paymentdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379